import { Component, OnInit, Pipe } from '@angular/core';

@Component({
  selector: 'eeAntonyms',
  templateUrl: './antonyms.component.html',
  styleUrls: ['./antonyms.component.less'],
})
export class AntonymsComponent implements OnInit {
    
  constructor() {
    this.max_score_ever = localStorage.getItem('max_score_ever');
  }
  max_score: number;
  max_score_ever;
  ngOnInit() {
    this.max_score = 0;
    this.select_random(5);
  }
  correct_last = undefined
  on_game_left = []
  on_game_right = []
  temp_left = undefined
  temp_right = undefined
  validation = {}
  options_used = []
  win = false
  
  reload(){
    this.max_score = 0;
    this.win=false
    this.options_antonyms = this.options_used.concat(this.options_antonyms);
    this.select_random(5)

  }
  select_random(n:number){
    if (this.options_antonyms.length < n){
        this.win = true;
        return;
    }
    for (let i = 0; i < n; i++) {
        let random = Math.floor(Math.random() * this.options_antonyms.length);
        this.on_game_left.push(this.options_antonyms[random][0]);
        this.on_game_right.push(this.options_antonyms[random][1]);
        this.options_used.push(this.options_antonyms[random]);
        this.validation[this.options_antonyms[random][0].en] = this.options_antonyms[random][1].en;
        this.options_antonyms.splice(random, 1);
    }
    this.on_game_left = this.on_game_left.sort(() => Math.random() - 0.5);
    this.on_game_right = this.on_game_right.sort(() => Math.random() - 0.5);
    }

    select_option(word, option){
        option == "left" ? this.temp_left = word : this.temp_right = word;
        if (this.temp_right !== undefined && this.temp_left !== undefined){
            if (this.temp_right.en === this.validation[this.temp_left.en]){
                this.max_score += 1;
                if (this.max_score > this.max_score_ever){
                    this.max_score_ever = this.max_score;
                    localStorage.setItem('max_score_ever', this.max_score_ever);
                }
                this.correct_last = this.temp_left.en + " ("+ this.temp_left.es + ")"
                this.correct_last = this.correct_last + " - " + this.temp_right.en + " ("+ this.temp_right.es + ")";
                this.on_game_left = this.on_game_left.filter((item) => item.en !== this.temp_left.en);
                this.on_game_right = this.on_game_right.filter((item) => item.en !== this.temp_right.en);
                this.temp_right = undefined;
                this.temp_left = undefined;
                if (this.on_game_left.length === 0){
                    this.select_random(5);
                }
            }
        }
    }
    


  options_antonyms = [
    [{"es":"Abierto","en":"Open"}, {"es":"Cerrado","en":"Closed"}],
    [{"es":"Activo","en":"Active"}, {"es":"Pasivo","en":"Passive"}],
    [{"es":"Alto","en":"High"}, {"es":"Bajo","en":"Low"}],
    [{"es":"Amargo","en":"Bitter"}, {"es":"Dulce","en":"Sweet"}],
    [{"es":"Antiguo","en":"Ancient"}, {"es":"Moderno","en":"Modern"}],
    [{"es":"Ascender","en":"Ascend"}, {"es":"Descender","en":"Descend"}],
    [{"es":"Atractivo","en":"Attractive"}, {"es":"Repulsivo","en":"Repulsive"}],
    [{"es":"Barato","en":"Cheap"}, {"es":"Caro","en":"Expensive"}],
    [{"es":"Blando","en":"Soft"}, {"es":"Duro","en":"Hard"}],
    [{"es":"Brillante","en":"Bright"}, {"es":"Oscuro","en":"Dark"}],
    [{"es":"Caliente","en":"Hot"}, {"es":"Frío","en":"Cold"}],
    [{"es":"Claro","en":"Clear"}, {"es":"Confuso","en":"Confusing"}],
    [{"es":"Comenzar","en":"Begin"}, {"es":"Terminar","en":"End"}],
    [{"es":"Común","en":"Common"}, {"es":"Raro","en":"Rare"}],
    [{"es":"Complejo","en":"Complex"}, {"es":"Simple","en":"Simple"}],
    [{"es":"Comprimir","en":"Compress"}, {"es":"Expandir","en":"Expand"}],
    [{"es":"Conectar","en":"Connect"}, {"es":"Desconectar","en":"Disconnect"}],
    [{"es":"Consciente","en":"Conscious"}, {"es":"Inconsciente","en":"Unconscious"}],
    [{"es":"Constante","en":"Constant"}, {"es":"Variable","en":"Variable"}],
    [{"es":"Construir","en":"Build"}, {"es":"Destruir","en":"Destroy"}],
    [{"es":"Contenido","en":"Content"}, {"es":"Insatisfecho","en":"Discontented"}],
    [{"es":"Convexo","en":"Convex"}, {"es":"Cóncavo","en":"Concave"}],
    [{"es":"Creer","en":"Believe"}, {"es":"Dudar","en":"Doubt"}],
    [{"es":"Cruel","en":"Cruel"}, {"es":"Amable","en":"Kind"}],
    [{"es":"Despierto","en":"Awake"}, {"es":"Dormido","en":"Asleep"}],
    [{"es":"Difícil","en":"Difficult"}, {"es":"Fácil","en":"Easy"}],
    [{"es":"Dulce","en":"Sweet"}, {"es":"Salado","en":"Salty"}],
    [{"es":"Encender","en":"Turn on"}, {"es":"Apagar","en":"Turn off"}],
    [{"es":"Enorme","en":"Huge"}, {"es":"Pequeño","en":"Small"}],
    [{"es":"Estrecho","en":"Narrow"}, {"es":"Ancho","en":"Wide"}],
    [{"es":"Exterior","en":"Exterior"}, {"es":"Interior","en":"Interior"}],
    [{"es":"Flexible","en":"Flexible"}, {"es":"Rígido","en":"Rigid"}],
    [{"es":"Fuerte","en":"Strong"}, {"es":"Débil","en":"Weak"}],
    [{"es":"Ganar","en":"Win"}, {"es":"Perder","en":"Lose"}],
    [{"es":"General","en":"General"}, {"es":"Específico","en":"Specific"}],
    [{"es":"Grueso","en":"Thick"}, {"es":"Delgado","en":"Thin"}],
    [{"es":"Húmedo","en":"Wet"}, {"es":"Seco","en":"Dry"}],
    [{"es":"Ignorar","en":"Ignore"}, {"es":"Notar","en":"Notice"}],
    [{"es":"Igual","en":"Equal"}, {"es":"Desigual","en":"Unequal"}],
    [{"es":"Iluminado","en":"Illuminated"}, {"es":"Oscurecido","en":"Obscured"}],
    [{"es":"Importante","en":"Important"}, {"es":"Trivial","en":"Trivial"}],
    [{"es":"Inocente","en":"Innocent"}, {"es":"Culpable","en":"Guilty"}],
    [{"es":"Joven","en":"Young"}, {"es":"Viejo","en":"Old"}],
    [{"es":"Largo","en":"Long"}, {"es":"Corto","en":"Short"}],
    [{"es":"Lento","en":"Slow"}, {"es":"Rápido","en":"Fast"}],
    [{"es":"Líquido","en":"Liquid"}, {"es":"Sólido","en":"Solid"}],
    [{"es":"Natural","en":"Natural"}, {"es":"Artificial","en":"Artificial"}],
    [{"es":"Normal","en":"Normal"}, {"es":"Anormal","en":"Abnormal"}],
    [{"es":"Nuevo","en":"New"}, {"es":"Viejo","en":"Old"}],
    [{"es":"Optimista","en":"Optimistic"}, {"es":"Pesimista","en":"Pessimistic"}],
    [{"es":"Abundante","en":"Abundant"}, {"es":"Escaso","en":"Scarce"}],
    [{"es":"Aceptable","en":"Acceptable"}, {"es":"Inaceptable","en":"Unacceptable"}],
    [{"es":"Alegre","en":"Cheerful"}, {"es":"Triste","en":"Sad"}],
    [{"es":"Amplio","en":"Broad"}, {"es":"Estrecho","en":"Narrow"}],
    [{"es":"Anterior","en":"Previous"}, {"es":"Siguiente","en":"Next"}],
    [{"es":"Apto","en":"Apt"}, {"es":"Inepto","en":"Inept"}],
    [{"es":"Artificial","en":"Artificial"}, {"es":"Natural","en":"Natural"}],
    [{"es":"Ascendente","en":"Ascending"}, {"es":"Descendente","en":"Descending"}],
    [{"es":"Audaz","en":"Bold"}, {"es":"Tímido","en":"Timid"}],
    [{"es":"Beneficioso","en":"Beneficial"}, {"es":"Perjudicial","en":"Harmful"}],
    [{"es":"Blanco","en":"White"}, {"es":"Negro","en":"Black"}],
    [{"es":"Bueno","en":"Good"}, {"es":"Malo","en":"Bad"}],
    [{"es":"Cálido","en":"Warm"}, {"es":"Frío","en":"Cold"}],
    [{"es":"Célebre","en":"Famous"}, {"es":"Desconocido","en":"Unknown"}],
    [{"es":"Central","en":"Central"}, {"es":"Periférico","en":"Peripheral"}],
    [{"es":"Cercano","en":"Near"}, {"es":"Lejano","en":"Far"}],
    [{"es":"Claro","en":"Light"}, {"es":"Oscuro","en":"Dark"}],
    [{"es":"Completo","en":"Complete"}, {"es":"Incompleto","en":"Incomplete"}],
    [{"es":"Complicado","en":"Complicated"}, {"es":"Simple","en":"Simple"}],
    [{"es":"Conectado","en":"Connected"}, {"es":"Desconectado","en":"Disconnected"}],
    [{"es":"Conformidad","en":"Conformity"}, {"es":"Disconformidad","en":"Nonconformity"}],
    [{"es":"Conservador","en":"Conservative"}, {"es":"Liberal","en":"Liberal"}],
    [{"es":"Constante","en":"Steady"}, {"es":"Inestable","en":"Unsteady"}],
    [{"es":"Controlado","en":"Controlled"}, {"es":"Descontrolado","en":"Uncontrolled"}],
    [{"es":"Convencional","en":"Conventional"}, {"es":"Inusual","en":"Unusual"}],
    [{"es":"Cooperativo","en":"Cooperative"}, {"es":"Obstinado","en":"Obstinate"}],
    [{"es":"Correcto","en":"Correct"}, {"es":"Incorrecto","en":"Incorrect"}],
    [{"es":"Delgado","en":"Thin"}, {"es":"Gordo","en":"Fat"}],
    [{"es":"Derecho","en":"Right"}, {"es":"Izquierdo","en":"Left"}],
    [{"es":"Despejado","en":"Clear"}, {"es":"Nublado","en":"Cloudy"}],
    [{"es":"Detallado","en":"Detailed"}, {"es":"General","en":"General"}],
    [{"es":"Difícil","en":"Hard"}, {"es":"Fácil","en":"Easy"}],
    [{"es":"Directo","en":"Direct"}, {"es":"Indirecto","en":"Indirect"}],
    [{"es":"Disponible","en":"Available"}, {"es":"No disponible","en":"Unavailable"}],
    [{"es":"Diverso","en":"Diverse"}, {"es":"Similar","en":"Similar"}],
    [{"es":"Eficiente","en":"Efficient"}, {"es":"Ineficiente","en":"Inefficient"}],
    [{"es":"Elástico","en":"Elastic"}, {"es":"Inelástico","en":"Inelastic"}],
    [{"es":"Emocionado","en":"Excited"}, {"es":"Indiferente","en":"Indifferent"}],
    [{"es":"Enérgico","en":"Energetic"}, {"es":"Letárgico","en":"Lethargic"}],
    [{"es":"Estable","en":"Stable"}, {"es":"Inestable","en":"Unstable"}],
    [{"es":"Estático","en":"Static"}, {"es":"Dinámico","en":"Dynamic"}],
    [{"es":"Exacto","en":"Exact"}, {"es":"Inexacto","en":"Inexact"}],
    [{"es":"Exterior","en":"Exterior"}, {"es":"Interior","en":"Interior"}],
    [{"es":"Extrovertido","en":"Extroverted"}, {"es":"Introvertido","en":"Introverted"}],
    [{"es":"Favorable","en":"Favorable"}, {"es":"Desfavorable","en":"Unfavorable"}],
    [{"es":"Fértil","en":"Fertile"}, {"es":"Estéril","en":"Sterile"}],
    [{"es":"Fijo","en":"Fixed"}, {"es":"Variable","en":"Variable"}],
    [{"es":"Final","en":"Final"}, {"es":"Inicial","en":"Initial"}],
    [{"es":"Flexible","en":"Flexible"}, {"es":"Rígido","en":"Rigid"}],
    [{"es":"Formal","en":"Formal"}, {"es":"Informal","en":"Informal"}],
    [{"es":"Frecuente","en":"Frequent"}, {"es":"Infrecuente","en":"Infrequent"}],
    [{"es":"Fresco","en":"Fresh"}, {"es":"Rancio","en":"Stale"}],
    [{"es":"Fuerte","en":"Strong"}, {"es":"Débil","en":"Weak"}],
    [{"es":"Ganador","en":"Winner"}, {"es":"Perdedor","en":"Loser"}],
    [{"es":"General","en":"General"}, {"es":"Específico","en":"Specific"}],
    [{"es":"Generoso","en":"Generous"}, {"es":"Avaro","en":"Greedy"}],
    [{"es":"Grande","en":"Big"}, {"es":"Pequeño","en":"Small"}],
    [{"es":"Grato","en":"Pleasant"}, {"es":"Desagradable","en":"Unpleasant"}],
    [{"es":"Guapo","en":"Handsome"}, {"es":"Feo","en":"Ugly"}],
    [{"es":"Hábil","en":"Skillful"}, {"es":"Torpe","en":"Clumsy"}],
    [{"es":"Hermoso","en":"Beautiful"}, {"es":"Feo","en":"Ugly"}],
    [{"es":"Heterogéneo","en":"Heterogeneous"}, {"es":"Homogéneo","en":"Homogeneous"}],
    [{"es":"Hilarante","en":"Hilarious"}, {"es":"Serio","en":"Serious"}],
    [{"es":"Honrado","en":"Honest"}, {"es":"Deshonesto","en":"Dishonest"}],
    [{"es":"Horizontal","en":"Horizontal"}, {"es":"Vertical","en":"Vertical"}],
    [{"es":"Humilde","en":"Humble"}, {"es":"Orgulloso","en":"Proud"}],
    [{"es":"Igual","en":"Equal"}, {"es":"Desigual","en":"Unequal"}],
    [{"es":"Importante","en":"Important"}, {"es":"Insignificante","en":"Insignificant"}],
    [{"es":"Incompleto","en":"Incomplete"}, {"es":"Completo","en":"Complete"}],
    [{"es":"Inconsciente","en":"Unconscious"}, {"es":"Consciente","en":"Conscious"}],
    [{"es":"Independiente","en":"Independent"}, {"es":"Dependiente","en":"Dependent"}],
    [{"es":"Inestable","en":"Unstable"}, {"es":"Estable","en":"Stable"}],
    [{"es":"Inferior","en":"Inferior"}, {"es":"Superior","en":"Superior"}],
    [{"es":"Inflexible","en":"Inflexible"}, {"es":"Flexible","en":"Flexible"}],
    [{"es":"Inocente","en":"Innocent"}, {"es":"Culpable","en":"Guilty"}],
    [{"es":"Inseguro","en":"Insecure"}, {"es":"Seguro","en":"Secure"}],
    [{"es":"Inteligente","en":"Intelligent"}, {"es":"Tonto","en":"Stupid"}],
    [{"es":"Interesante","en":"Interesting"}, {"es":"Aburrido","en":"Boring"}],
    [{"es":"Interno","en":"Internal"}, {"es":"Externo","en":"External"}],
    [{"es":"Inusual","en":"Unusual"}, {"es":"Común","en":"Common"}],
    [{"es":"Joven","en":"Young"}, {"es":"Viejo","en":"Old"}],
    [{"es":"Justo","en":"Fair"}, {"es":"Injusto","en":"Unfair"}],
    [{"es":"Largo","en":"Long"}, {"es":"Corto","en":"Short"}],
    [{"es":"Lento","en":"Slow"}, {"es":"Rápido","en":"Fast"}],
    [{"es":"Leve","en":"Slight"}, {"es":"Grave","en":"Serious"}],
    [{"es":"Libre","en":"Free"}, {"es":"Ocupado","en":"Busy"}],
    [{"es":"Limpio","en":"Clean"}, {"es":"Sucio","en":"Dirty"}],
    [{"es":"Listo","en":"Ready"}, {"es":"No listo","en":"Not ready"}],
    [{"es":"Lleno","en":"Full"}, {"es":"Vacío","en":"Empty"}],
    [{"es":"Lógico","en":"Logical"}, {"es":"Ilógico","en":"Illogical"}],
    [{"es":"Luminoso","en":"Bright"}, {"es":"Opaco","en":"Dull"}],
    [{"es":"Malo","en":"Bad"}, {"es":"Bueno","en":"Good"}],
    [{"es":"Mayor","en":"Elder"}, {"es":"Menor","en":"Younger"}],
    [{"es":"Mejor","en":"Better"}, {"es":"Peor","en":"Worse"}],
    [{"es":"Mínimo","en":"Minimum"}, {"es":"Máximo","en":"Maximum"}],
    [{"es":"Móvil","en":"Mobile"}, {"es":"Fijo","en":"Fixed"}],
    [{"es":"Muerto","en":"Dead"}, {"es":"Vivo","en":"Alive"}],
    [{"es":"Natural","en":"Natural"}, {"es":"Artificial","en":"Artificial"}],
    [{"es":"Negativo","en":"Negative"}, {"es":"Positivo","en":"Positive"}],
    [{"es":"Normal","en":"Normal"}, {"es":"Anormal","en":"Abnormal"}],
    [{"es":"Nuevo","en":"New"}, {"es":"Viejo","en":"Old"}],
    [{"es":"Obligatorio","en":"Obligatory"}, {"es":"Opcional","en":"Optional"}],
    [{"es":"Oculto","en":"Hidden"}, {"es":"Visible","en":"Visible"}],
    [{"es":"Ofensivo","en":"Offensive"}, {"es":"Defensivo","en":"Defensive"}],
    [{"es":"Optimista","en":"Optimistic"}, {"es":"Pesimista","en":"Pessimistic"}],
    [{"es":"Ordenado","en":"Ordered"}, {"es":"Desordenado","en":"Disordered"}],
    [{"es":"Original","en":"Original"}, {"es":"Copiado","en":"Copied"}],
    [{"es":"Paciente","en":"Patient"}, {"es":"Impaciente","en":"Impatient"}],
    [{"es":"Pálido","en":"Pale"}, {"es":"Moreno","en":"Brown"}],
    [{"es":"Pequeño","en":"Small"}, {"es":"Grande","en":"Big"}],
    [{"es":"Permanente","en":"Permanent"}, {"es":"Temporal","en":"Temporary"}],
    [{"es":"Pobre","en":"Poor"}, {"es":"Rico","en":"Rich"}],
    [{"es":"Posible","en":"Possible"}, {"es":"Imposible","en":"Impossible"}],
    [{"es":"Preciso","en":"Precise"}, {"es":"Impreciso","en":"Imprecise"}],
    [{"es":"Presente","en":"Present"}, {"es":"Ausente","en":"Absent"}],
    [{"es":"Principiante","en":"Beginner"}, {"es":"Experto","en":"Expert"}],
    [{"es":"Privado","en":"Private"}, {"es":"Público","en":"Public"}],
    [{"es":"Profundo","en":"Deep"}, {"es":"Superficial","en":"Superficial"}],
    [{"es":"Rápido","en":"Fast"}, {"es":"Lento","en":"Slow"}],
    [{"es":"Raro","en":"Rare"}, {"es":"Común","en":"Common"}],
    [{"es":"Real","en":"Real"}, {"es":"Falso","en":"False"}],
    [{"es":"Rechazado","en":"Rejected"}, {"es":"Aceptado","en":"Accepted"}],
    [{"es":"Rico","en":"Rich"}, {"es":"Pobre","en":"Poor"}],
    [{"es":"Rígido","en":"Rigid"}, {"es":"Flexible","en":"Flexible"}],
    [{"es":"Roto","en":"Broken"}, {"es":"Entero","en":"Whole"}],
    [{"es":"Ruidoso","en":"Noisy"}, {"es":"Silencioso","en":"Silent"}],
    [{"es":"Sano","en":"Healthy"}, {"es":"Enfermo","en":"Sick"}],
    [{"es":"Seco","en":"Dry"}, {"es":"Húmedo","en":"Wet"}],
    [{"es":"Seguro","en":"Safe"}, {"es":"Inseguro","en":"Unsafe"}],
    [{"es":"Sencillo","en":"Simple"}, {"es":"Complicado","en":"Complicated"}],
    [{"es":"Serio","en":"Serious"}, {"es":"Divertido","en":"Funny"}],
    [{"es":"Simple","en":"Simple"}, {"es":"Complicado","en":"Complicated"}],
    [{"es":"Sincero","en":"Sincere"}, {"es":"Falso","en":"False"}],
    [{"es":"Sólido","en":"Solid"}, {"es":"Líquido","en":"Liquid"}],
    [{"es":"Sorprendente","en":"Surprising"}, {"es":"Predecible","en":"Predictable"}],
    [{"es":"Superior","en":"Superior"}, {"es":"Inferior","en":"Inferior"}],
    [{"es":"Tardío","en":"Late"}, {"es":"Temprano","en":"Early"}],
    [{"es":"Terco","en":"Stubborn"}, {"es":"Flexible","en":"Flexible"}],
    [{"es":"Tímido","en":"Shy"}, {"es":"Audaz","en":"Bold"}],
    [{"es":"Tranquilo","en":"Calm"}, {"es":"Nervioso","en":"Nervous"}],
    [{"es":"Triste","en":"Sad"}, {"es":"Feliz","en":"Happy"}],
    [{"es":"Universal","en":"Universal"}, {"es":"Particular","en":"Particular"}],
    [{"es":"Urbano","en":"Urban"}, {"es":"Rural","en":"Rural"}],
    [{"es":"Útil","en":"Useful"}, {"es":"Inútil","en":"Useless"}],
    [{"es":"Válido","en":"Valid"}, {"es":"Inválido","en":"Invalid"}],
    [{"es":"Verdadero","en":"True"}, {"es":"Falso","en":"False"}],
    [{"es":"Vivo","en":"Alive"}, {"es":"Muerto","en":"Dead"}],
    [{"es":"Volátil","en":"Volatile"}, {"es":"Estable","en":"Stable"}],
    [{"es":"Voluntario","en":"Voluntary"}, {"es":"Obligatorio","en":"Obligatory"}],
    [{"es":"Zurdo","en":"Left-handed"}, {"es":"Diestro","en":"Right-handed"}],
    [{"es":"Aclarar","en":"Clarify"}, {"es":"Confundir","en":"Confuse"}],
    [{"es":"Amar","en":"Love"}, {"es":"Odiar","en":"Hate"}],
    [{"es":"Amplio","en":"Broad"}, {"es":"Estrecho","en":"Narrow"}],
    [{"es":"Ancho","en":"Wide"}, {"es":"Estrecho","en":"Narrow"}],
    [{"es":"Aparecer","en":"Appear"}, {"es":"Desaparecer","en":"Disappear"}],
    [{"es":"Apoyar","en":"Support"}, {"es":"Oponerse","en":"Oppose"}],
    [{"es":"Aprobar","en":"Approve"}, {"es":"Desaprobar","en":"Disapprove"}],
    [{"es":"Arriba","en":"Up"}, {"es":"Abajo","en":"Down"}],
    [{"es":"Atacar","en":"Attack"}, {"es":"Defender","en":"Defend"}],
    [{"es":"Aumentar","en":"Increase"}, {"es":"Disminuir","en":"Decrease"}],
    [{"es":"Bajar","en":"Go down"}, {"es":"Subir","en":"Go up"}],
    [{"es":"Bendecir","en":"Bless"}, {"es":"Maldecir","en":"Curse"}],
    [{"es":"Borrar","en":"Erase"}, {"es":"Escribir","en":"Write"}],
    [{"es":"Brillar","en":"Shine"}, {"es":"Ocultar","en":"Hide"}],
    [{"es":"Cargar","en":"Load"}, {"es":"Descargar","en":"Unload"}],
    [{"es":"Cauteloso","en":"Cautious"}, {"es":"Descuidado","en":"Careless"}],
    [{"es":"Cerrar","en":"Close"}, {"es":"Abrir","en":"Open"}],
    [{"es":"Citar","en":"Quote"}, {"es":"Omitir","en":"Omit"}],
    [{"es":"Colocar","en":"Place"}, {"es":"Quitar","en":"Remove"}],
    [{"es":"Comenzar","en":"Start"}, {"es":"Terminar","en":"Finish"}],
    [{"es":"Comer","en":"Eat"}, {"es":"Ayunar","en":"Fast"}],
    [{"es":"Comprar","en":"Buy"}, {"es":"Vender","en":"Sell"}],
    [{"es":"Conectar","en":"Connect"}, {"es":"Desconectar","en":"Disconnect"}],
    [{"es":"Conquistar","en":"Conquer"}, {"es":"Rendirse","en":"Surrender"}],
    [{"es":"Construir","en":"Build"}, {"es":"Destruir","en":"Destroy"}],
    [{"es":"Continuar","en":"Continue"}, {"es":"Detener","en":"Stop"}],
    [{"es":"Convencer","en":"Convince"}, {"es":"Desconvencer","en":"Dissuade"}],
    [{"es":"Crear","en":"Create"}, {"es":"Destruir","en":"Destroy"}],
    [{"es":"Crecer","en":"Grow"}, {"es":"Disminuir","en":"Decrease"}],
    [{"es":"Critica","en":"Criticize"}, {"es":"Alabar","en":"Praise"}],
    [{"es":"Cruzar","en":"Cross"}, {"es":"Descruzar","en":"Uncross"}],
    [{"es":"Cuidar","en":"Care"}, {"es":"Descuidar","en":"Neglect"}],
    [{"es":"Cumplir","en":"Fulfill"}, {"es":"Incumplir","en":"Fail"}],
    [{"es":"Dar","en":"Give"}, {"es":"Recibir","en":"Receive"}],
    [{"es":"Decir","en":"Say"}, {"es":"Callar","en":"Silence"}],
    [{"es":"Decrecer","en":"Decrease"}, {"es":"Aumentar","en":"Increase"}],
    [{"es":"Defender","en":"Defend"}, {"es":"Atacar","en":"Attack"}],
    [{"es":"Demostrar","en":"Prove"}, {"es":"Desmentir","en":"Disprove"}],
    [{"es":"Desaparecer","en":"Disappear"}, {"es":"Aparecer","en":"Appear"}],
    [{"es":"Desarrollar","en":"Develop"}, {"es":"Destruir","en":"Destroy"}],
    [{"es":"Descender","en":"Descend"}, {"es":"Ascender","en":"Ascend"}],
    [{"es":"A tiempo","en":"On time"}, {"es":"Tarde","en":"Late"}],
    [{"es":"Abierto","en":"Open"}, {"es":"Cerrado","en":"Closed"}],
    [{"es":"Activo","en":"Active"}, {"es":"Inactivo","en":"Inactive"}],
    [{"es":"Alto","en":"High"}, {"es":"Bajo","en":"Low"}],
    [{"es":"Amplio","en":"Wide"}, {"es":"Estrecho","en":"Narrow"}],
    [{"es":"Ascendente","en":"Ascending"}, {"es":"Descendente","en":"Descending"}],
    [{"es":"Asociado","en":"Associate"}, {"es":"Separado","en":"Separate"}],
    [{"es":"Autónomo","en":"Autonomous"}, {"es":"Dependiente","en":"Dependent"}],
    [{"es":"Beneficioso","en":"Beneficial"}, {"es":"Perjudicial","en":"Harmful"}],
    [{"es":"Calificado","en":"Qualified"}, {"es":"No calificado","en":"Unqualified"}],
    [{"es":"Capaz","en":"Capable"}, {"es":"Incapaz","en":"Incapable"}],
    [{"es":"Central","en":"Central"}, {"es":"Periférico","en":"Peripheral"}],
    [{"es":"Colaborativo","en":"Collaborative"}, {"es":"Competitivo","en":"Competitive"}],
    [{"es":"Completo","en":"Complete"}, {"es":"Incompleto","en":"Incomplete"}],
    [{"es":"Constructivo","en":"Constructive"}, {"es":"Destructivo","en":"Destructive"}],
    [{"es":"Continuo","en":"Continuous"}, {"es":"Intermitente","en":"Intermittent"}],
    [{"es":"Contratado","en":"Hired"}, {"es":"Despedido","en":"Fired"}],
    [{"es":"Cooperativo","en":"Cooperative"}, {"es":"Obstinado","en":"Obstinate"}],
    [{"es":"Correcto","en":"Correct"}, {"es":"Incorrecto","en":"Incorrect"}],
    [{"es":"Creciente","en":"Growing"}, {"es":"Decreciente","en":"Decreasing"}],
    [{"es":"Dedicado","en":"Dedicated"}, {"es":"Indiferente","en":"Indifferent"}],
    [{"es":"Desafiante","en":"Challenging"}, {"es":"Fácil","en":"Easy"}],
    [{"es":"Desarrollado","en":"Developed"}, {"es":"Subdesarrollado","en":"Underdeveloped"}],
    [{"es":"Dinámico","en":"Dynamic"}, {"es":"Estático","en":"Static"}],
    [{"es":"Directo","en":"Direct"}, {"es":"Indirecto","en":"Indirect"}],
    [{"es":"Disciplinado","en":"Disciplined"}, {"es":"Indisciplinado","en":"Undisciplined"}],
    [{"es":"Disponible","en":"Available"}, {"es":"No disponible","en":"Unavailable"}],
    [{"es":"Diversificado","en":"Diversified"}, {"es":"Homogéneo","en":"Homogeneous"}],
    [{"es":"Eficiente","en":"Efficient"}, {"es":"Ineficiente","en":"Inefficient"}],
    [{"es":"Elegible","en":"Eligible"}, {"es":"Inelegible","en":"Ineligible"}],
    [{"es":"Empleado","en":"Employed"}, {"es":"Desempleado","en":"Unemployed"}],
    [{"es":"Empoderado","en":"Empowered"}, {"es":"Desempoderado","en":"Disempowered"}],
    [{"es":"Encendido","en":"On"}, {"es":"Apagado","en":"Off"}],
    [{"es":"Enriquecedor","en":"Enriching"}, {"es":"Empobrecido","en":"Impoverishing"}],
    [{"es":"Equitativo","en":"Equitable"}, {"es":"Inequitativo","en":"Inequitable"}],
    [{"es":"Estable","en":"Stable"}, {"es":"Inestable","en":"Unstable"}],
    [{"es":"Estratégico","en":"Strategic"}, {"es":"No estratégico","en":"Non-strategic"}],
    [{"es":"Estructurado","en":"Structured"}, {"es":"Desestructurado","en":"Unstructured"}],
    [{"es":"Ético","en":"Ethical"}, {"es":"No ético","en":"Unethical"}],
    [{"es":"Excluido","en":"Excluded"}, {"es":"Incluido","en":"Included"}],
    [{"es":"Externo","en":"External"}, {"es":"Interno","en":"Internal"}],
    [{"es":"Flexible","en":"Flexible"}, {"es":"Rígido","en":"Rigid"}],
    [{"es":"Formal","en":"Formal"}, {"es":"Informal","en":"Informal"}],
    [{"es":"Fuerte","en":"Strong"}, {"es":"Débil","en":"Weak"}],
    [{"es":"Funcional","en":"Functional"}, {"es":"No funcional","en":"Non-functional"}],
    [{"es":"General","en":"General"}, {"es":"Específico","en":"Specific"}],
    [{"es":"Generoso","en":"Generous"}, {"es":"Tacaño","en":"Stingy"}],
    [{"es":"Global","en":"Global"}, {"es":"Local","en":"Local"}],
    [{"es":"Grave","en":"Serious"}, {"es":"Leve","en":"Mild"}],
    [{"es":"Hábil","en":"Skillful"}, {"es":"Inhábil","en":"Unskillful"}],
    [{"es":"Horizontal","en":"Horizontal"}, {"es":"Vertical","en":"Vertical"}],
    [{"es":"Importante","en":"Important"}, {"es":"Trivial","en":"Trivial"}],
    [{"es":"Impulsivo","en":"Impulsive"}, {"es":"Considerado","en":"Considerate"}],
    [{"es":"Inclusivo","en":"Inclusive"}, {"es":"Exclusivo","en":"Exclusive"}],
    [{"es":"Incremental","en":"Incremental"}, {"es":"Radical","en":"Radical"}],
    [{"es":"Independiente","en":"Independent"}, {"es":"Dependiente","en":"Dependent"}],
    [{"es":"Innovador","en":"Innovative"}, {"es":"Convencional","en":"Conventional"}],
    [{"es":"Inspirador","en":"Inspirational"}, {"es":"Desmotivador","en":"Demotivating"}],
    [{"es":"Integrado","en":"Integrated"}, {"es":"Segmentado","en":"Segmented"}],
    [{"es":"Intenso","en":"Intense"}, {"es":"Moderado","en":"Moderate"}],
    [{"es":"Intermitente","en":"Intermittent"}, {"es":"Continuo","en":"Continuous"}],
    [{"es":"Interno","en":"Internal"}, {"es":"Externo","en":"External"}],
    [{"es":"Justo","en":"Fair"}, {"es":"Injusto","en":"Unfair"}],
    [{"es":"Legal","en":"Legal"}, {"es":"Ilegal","en":"Illegal"}],
    [{"es":"Ligero","en":"Light"}, {"es":"Pesado","en":"Heavy"}],
    [{"es":"Limitado","en":"Limited"}, {"es":"Ilimitado","en":"Unlimited"}],
    [{"es":"Lógico","en":"Logical"}, {"es":"Ilógico","en":"Illogical"}],
    [{"es":"Mayor","en":"Major"}, {"es":"Menor","en":"Minor"}],
    [{"es":"Medido","en":"Measured"}, {"es":"Desmedido","en":"Immeasurable"}],
    [{"es":"Moderno","en":"Modern"}, {"es":"Antiguo","en":"Ancient"}],
    [{"es":"Motivado","en":"Motivated"}, {"es":"Desmotivado","en":"Demotivated"}],
    [{"es":"Necesario","en":"Necessary"}, {"es":"Innecesario","en":"Unnecessary"}],
    [{"es":"Negativo","en":"Negative"}, {"es":"Positivo","en":"Positive"}],
    [{"es":"Normal","en":"Normal"}, {"es":"Anormal","en":"Abnormal"}],
    [{"es":"Nuevo","en":"New"}, {"es":"Viejo","en":"Old"}],
    [{"es":"Oficial","en":"Official"}, {"es":"No oficial","en":"Unofficial"}],
    [{"es":"Óptimo","en":"Optimal"}, {"es":"Pésimo","en":"Pessimal"}],
    [{"es":"Organizado","en":"Organized"}, {"es":"Desorganizado","en":"Disorganized"}],
    [{"es":"Orientado al detalle","en":"Detail-oriented"}, {"es":"Descuidado","en":"Careless"}],
    [{"es":"Parcial","en":"Partial"}, {"es":"Completo","en":"Complete"}],
    [{"es":"Pasivo","en":"Passive"}, {"es":"Activo","en":"Active"}],
    [{"es":"Permanente","en":"Permanent"}, {"es":"Temporal","en":"Temporary"}],
    [{"es":"Posible","en":"Possible"}, {"es":"Imposible","en":"Impossible"}],
    [{"es":"Preciso","en":"Precise"}, {"es":"Impreciso","en":"Imprecise"}],
    [{"es":"Presente","en":"Present"}, {"es":"Ausente","en":"Absent"}],
    [{"es":"Previsible","en":"Predictable"}, {"es":"Imprevisible","en":"Unpredictable"}],
    [{"es":"Principal","en":"Principal"}, {"es":"Secundario","en":"Secondary"}],
    [{"es":"Privado","en":"Private"}, {"es":"Público","en":"Public"}],
    [{"es":"Productivo","en":"Productive"}, {"es":"Improductivo","en":"Unproductive"}],
    [{"es":"Profesional","en":"Professional"}, {"es":"Amateur","en":"Amateur"}],
    [{"es":"Progresivo","en":"Progressive"}, {"es":"Regresivo","en":"Regressive"}],
    [{"es":"Promovido","en":"Promoted"}, {"es":"Degradado","en":"Demoted"}],
    [{"es":"Próspero","en":"Prosperous"}, {"es":"Decadente","en":"Decaying"}],
    [{"es":"Protegido","en":"Protected"}, {"es":"Expuesto","en":"Exposed"}],
    [{"es":"Provisional","en":"Provisional"}, {"es":"Definitivo","en":"Definitive"}],
    [{"es":"Puntual","en":"Punctual"}, {"es":"Impuntual","en":"Unpunctual"}],
    [{"es":"Rápido","en":"Fast"}, {"es":"Lento","en":"Slow"}],
    [{"es":"Realista","en":"Realistic"}, {"es":"Irrealista","en":"Unrealistic"}],
    [{"es":"Regular","en":"Regular"}, {"es":"Irregular","en":"Irregular"}],
    [{"es":"Relevante","en":"Relevant"}, {"es":"Irrelevante","en":"Irrelevant"}],
    [{"es":"Remoto","en":"Remote"}, {"es":"Presencial","en":"On-site"}],
    [{"es":"Rentable","en":"Profitable"}, {"es":"No rentable","en":"Unprofitable"}],
    [{"es":"Reparable","en":"Repairable"}, {"es":"Irreparable","en":"Irreparable"}],
    [{"es":"Repetitivo","en":"Repetitive"}, {"es":"Variado","en":"Varied"}],
    [{"es":"Reservado","en":"Reserved"}, {"es":"Extrovertido","en":"Outgoing"}],
    [{"es":"Responsable","en":"Responsible"}, {"es":"Irresponsable","en":"Irresponsible"}],
    [{"es":"Rígido","en":"Rigid"}, {"es":"Flexible","en":"Flexible"}],
    [{"es":"Rutinario","en":"Routine"}, {"es":"Extraordinario","en":"Extraordinary"}],
    [{"es":"Seguro","en":"Safe"}, {"es":"Peligroso","en":"Dangerous"}],
    [{"es":"Serio","en":"Serious"}, {"es":"Jovial","en":"Jovial"}],
    [{"es":"Simple","en":"Simple"}, {"es":"Complejo","en":"Complex"}],
    [{"es":"Sincero","en":"Sincere"}, {"es":"Insincero","en":"Insincere"}],
    [{"es":"Singular","en":"Singular"}, {"es":"Plural","en":"Plural"}],
    [{"es":"Sólido","en":"Solid"}, {"es":"Líquido","en":"Liquid"}],
    [{"es":"Sostenible","en":"Sustainable"}, {"es":"Insostenible","en":"Unsustainable"}],
    [{"es":"Subjetivo","en":"Subjective"}, {"es":"Objetivo","en":"Objective"}],
    [{"es":"Superficial","en":"Superficial"}, {"es":"Profundo","en":"Deep"}],
    [{"es":"Superior","en":"Superior"}, {"es":"Inferior","en":"Inferior"}],
    [{"es":"Temporal","en":"Temporary"}, {"es":"Permanente","en":"Permanent"}],
    [{"es":"Transparente","en":"Transparent"}, {"es":"Opaco","en":"Opaque"}],
    [{"es":"Útil","en":"Useful"}, {"es":"Inútil","en":"Useless"}],
    [{"es":"Visible","en":"Visible"}, {"es":"Invisible","en":"Invisible"}],
    [{"es":"Volátil","en":"Volatile"}, {"es":"Estable","en":"Stable"}],
    [{"es":"Accesible","en":"Accessible"}, {"es":"Inaccesible","en":"Inaccessible"}],
    [{"es":"Activo","en":"Active"}, {"es":"Inactivo","en":"Inactive"}],
    [{"es":"Analógico","en":"Analog"}, {"es":"Digital","en":"Digital"}],
    [{"es":"Automatizado","en":"Automated"}, {"es":"Manual","en":"Manual"}],
    [{"es":"Binario","en":"Binary"}, {"es":"Decimal","en":"Decimal"}],
    [{"es":"Centralizado","en":"Centralized"}, {"es":"Descentralizado","en":"Decentralized"}],
    [{"es":"Cliente","en":"Client"}, {"es":"Servidor","en":"Server"}],
    [{"es":"Compilado","en":"Compiled"}, {"es":"Interpretado","en":"Interpreted"}],
    [{"es":"Comprimido","en":"Compressed"}, {"es":"Descomprimido","en":"Uncompressed"}],
    [{"es":"Conectado","en":"Connected"}, {"es":"Desconectado","en":"Disconnected"}],
    [{"es":"Consistente","en":"Consistent"}, {"es":"Inconsistente","en":"Inconsistent"}],
    [{"es":"Dinámico","en":"Dynamic"}, {"es":"Estático","en":"Static"}],
    [{"es":"Directo","en":"Direct"}, {"es":"Indirecto","en":"Indirect"}],
    [{"es":"Duro","en":"Hard"}, {"es":"Blando","en":"Soft"}],
    [{"es":"Eficiente","en":"Efficient"}, {"es":"Ineficiente","en":"Inefficient"}],
    [{"es":"Entrada","en":"Input"}, {"es":"Salida","en":"Output"}],
    [{"es":"Estable","en":"Stable"}, {"es":"Inestable","en":"Unstable"}],
    [{"es":"Estático","en":"Static"}, {"es":"Dinámico","en":"Dynamic"}],
    [{"es":"Externo","en":"External"}, {"es":"Interno","en":"Internal"}],
    [{"es":"Fijo","en":"Fixed"}, {"es":"Variable","en":"Variable"}],
    [{"es":"Frontend","en":"Frontend"}, {"es":"Backend","en":"Backend"}],
    [{"es":"Funcional","en":"Functional"}, {"es":"No funcional","en":"Non-functional"}],
    [{"es":"Global","en":"Global"}, {"es":"Local","en":"Local"}],
    [{"es":"Horizontal","en":"Horizontal"}, {"es":"Vertical","en":"Vertical"}],
    [{"es":"Incremental","en":"Incremental"}, {"es":"Completo","en":"Full"}],
    [{"es":"Lógico","en":"Logical"}, {"es":"Físico","en":"Physical"}],
    [{"es":"Mayor","en":"Major"}, {"es":"Menor","en":"Minor"}],
    [{"es":"Móvil","en":"Mobile"}, {"es":"Estacionario","en":"Stationary"}],
    [{"es":"Modular","en":"Modular"}, {"es":"Monolítico","en":"Monolithic"}],
    [{"es":"Nativo","en":"Native"}, {"es":"Interpretado","en":"Interpreted"}],
    [{"es":"Normal","en":"Normal"}, {"es":"Anormal","en":"Abnormal"}],
    [{"es":"Objeto","en":"Object"}, {"es":"Sujeto","en":"Subject"}],
    [{"es":"Offline","en":"Offline"}, {"es":"Online","en":"Online"}],
    [{"es":"Optimizado","en":"Optimized"}, {"es":"No optimizado","en":"Unoptimized"}],
    [{"es":"Paralelo","en":"Parallel"}, {"es":"Serial","en":"Serial"}],
    [{"es":"Permanente","en":"Permanent"}, {"es":"Temporal","en":"Temporary"}],
    [{"es":"Primario","en":"Primary"}, {"es":"Secundario","en":"Secondary"}],
    [{"es":"Privado","en":"Private"}, {"es":"Público","en":"Public"}],
    [{"es":"Protegido","en":"Protected"}, {"es":"Expuesto","en":"Exposed"}],
    [{"es":"Provisional","en":"Provisional"}, {"es":"Definitivo","en":"Definitive"}],
    [{"es":"Rápido","en":"Fast"}, {"es":"Lento","en":"Slow"}],
    [{"es":"Real","en":"Real"}, {"es":"Virtual","en":"Virtual"}],
    [{"es":"Regular","en":"Regular"}, {"es":"Irregular","en":"Irregular"}],
    [{"es":"Remoto","en":"Remote"}, {"es":"Local","en":"Local"}],
    [{"es":"Reversible","en":"Reversible"}, {"es":"Irreversible","en":"Irreversible"}],
    [{"es":"Rígido","en":"Rigid"}, {"es":"Flexible","en":"Flexible"}],
    [{"es":"Simple","en":"Simple"}, {"es":"Complejo","en":"Complex"}],
    [{"es":"Sincronizado","en":"Synchronized"}, {"es":"Asincronizado","en":"Asynchronized"}],
    [{"es":"Superior","en":"Superior"}, {"es":"Inferior","en":"Inferior"}],
    [{"es":"Temporal","en":"Temporary"}, {"es":"Permanente","en":"Permanent"}],
    [{"es":"Transparente","en":"Transparent"}, {"es":"Opaco","en":"Opaque"}],
    [{"es":"Útil","en":"Useful"}, {"es":"Inútil","en":"Useless"}],
   [{"es":"Visible","en":"Visible"}, {"es":"Invisible","en":"Invisible"}]
];


}
